### ISSUE TITLE
Tool not working without sudo and nxc not working with sudo

### ISSUE THREAD

**Issue by josemlwdf** [DaddyBigFish/enumx#4]
When i launch it with sudo it does not work
![image](https://github.com/user-attachments/assets/3508497f-246c-41ca-84ea-3517f6c5fdee)

When launched with sudo nxc is not found because it was installed on the users home using pipx

![image](https://github.com/user-attachments/assets/bd327be3-cdc8-4016-a661-0fb3898c67cc)

**Comment by DaddyBigFish** [comment]
Wow.. sorry for that! Are you able to `locate nxc` and `locate netexec` please? I just want to check something

**Comment by DaddyBigFish** [comment]
it seems to be if nxc was installed with python, then it is not finding the command `nxc`

**Comment by DaddyBigFish** [comment]
when you type `nxc` into terminal or `netexec` separately does it give you the same error?

**Comment by DaddyBigFish** [comment]
what i will do is push an update now, to make sure it references to `netexec` instead of `nxc` it may be that the kali package via https://www.kali.org/tools/netexec/  also allows `nxc` but when installed via python it only allows `netexec`.

i'll update now and make all references to `netexec` instead :)

**Comment by DaddyBigFish** [comment]
Ok, I just updated the references to nxc as netexec.

Please can you run `enumx update`

Let me know if that fixes it or what error occurs now if any! :trophy: :pray:

**Comment by josemlwdf** [comment]
hello, i think the issue is that netexec when installed with pipx will be installed in the users home folder and not globally so maybe find a way to look for it in home when the app is running with sudo. This problem will not exists if netexec was installed also with sudo

**Comment by josemlwdf** [comment]
![image](https://github.com/user-attachments/assets/82df0431-0172-44a2-9c20-147b2d31f1fc)

**Comment by DaddyBigFish** [comment]
```
git clone https://github.com/DaddyBigFish/enumx.git ~/.git/enumx
chmod +x ~/.git/enumx/enumx
sudo ln -s ~/.git/enumx/enumx /usr/local/bin/enumx
```

I just realised now that the `netexec` was missing from the apt install aswell, so if you wished to update / install using the tool then you will need to re clone and `enumx install`

**Comment by josemlwdf** [comment]
![image](https://github.com/user-attachments/assets/a1fb8061-303a-4471-94cd-e94896f871ef)

**Comment by josemlwdf** [comment]
> ```
> git clone https://github.com/DaddyBigFish/enumx.git ~/.git/enumx
> chmod +x ~/.git/enumx/enumx
> sudo ln -s ~/.git/enumx/enumx /usr/local/bin/enumx
> ```
> 
> I just realised now that the `netexec` was missing from the apt install aswell, so if you wished to update / install using the tool then you will need to re clone and `enumx install`

i do not clone, i just wget the raw file LOL

**Comment by DaddyBigFish** [comment]
this tool is designed to be using just kali packages, for now at least, so it's best to install with kali package https://www.kali.org/tools/netexec/  `sudo apt install netexec`

**Comment by DaddyBigFish** [comment]
the latest tool update i just made added kali netexec package to the install list, can't believe i missed that one! :disappointed:

**Comment by josemlwdf** [comment]
actually, just find for this path suing a regex for the username before launch nxc and call it using the full path: 
![image](https://github.com/user-attachments/assets/dd7bc6f0-7076-4f66-8f79-0a81ae49002f)

**Comment by DaddyBigFish** [comment]
Yes, that's true! 

Does it still give you this error with Kali package? The tool is really designed just for Kali / Debian packages

**Comment by DaddyBigFish** [comment]
Here man try Kali for WSM https://www.kali.org/docs/wsl/wsl-preparations/ :pray:

**Comment by josemlwdf** [comment]
> Here man try Kali for WSL https://www.kali.org/docs/wsl/wsl-preparations/ 🙏

that's what i have but i use my own script: https://github.com/josemlwdf/random_scripts/blob/main/custom_wsl.sh
